name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: false

      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: golangci-lint run

      - name: Build
        run: |
          CGO_ENABLED=0 go build -ldflags ""

      - name: Get next tag name
        uses: reecetech/version-increment@2024.10.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        id: version
        with:
          scheme: semver
          increment: patch

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
