name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cache: false

      #      - name: golangci-lint
      #        uses: golangci/golangci-lint-action@v6
      #        with:
      #          version: v1.60

      - name: Build
        run: |
          CGO_ENABLED=0 go build -ldflags ""

      - name: Release new version
        env:
          GH_TOKEN: ${{ github.token }}
          GIT_TAG: "v0.0.2"
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |-
          git tag $GIT_TAG
